#!/bin/bash

# In this file:           #In BUSTEDPHchunks
#   $1                        the chunked file listing CDS files
#   $2                        the path to labelled phylogenies
#   $3                        the prefix for this trait


while read -r line;
do
  export cdsFile=$line
  export pathToTrees=$2
  export prefix=$3

  echo the coding sequence alignment file is $cdsFile
  # The tree file needs to look like OG0002680_tree.txt. $f looks like  /removedStops/labelled_cleaned_OG0002680_cds.fasta.
  export orthogroupNumber=`echo "$cdsFile" | awk -F'_' '{print ($2)}'`
  #echo The orthogroup number is $orthogroupNumber
  # 9_1_LabelledPhylogenies/workerPolymorphism/workerPolymorphismLabelled_OG0007231_tree.txt
  export treeFile="labelled_cleaned_"$orthogroupNumber"_tree.txt"
  echo the tree file is $pathToTrees$treeFile
  export catFile="./bustedPHResults/"$prefix"/"$prefix"_"$orthogroupNumber"_BUSTEDPH.fas"
  export inputFile="./bustedPHResults/"$prefix"/"$prefix"_"$orthogroupNumber"_BUSTEDPH.fas"
  export outputCheck="./bustedPHResults/"$prefix"/"$prefix"_"$orthogroupNumber"_BUSTEDPH.fas.BUSTED.json"
  if [ -f "$outputCheck" ]; then
      echo "$outputCheck exists; BUSTED-PH already performed on this orthogroup."
  else
    if [ -f "$pathToTrees$treeFile" ]; then
        echo "$pathToTrees$treeFile exists."
        if [ -f "$cdsFile" ]; then
            echo "$cdsFile exists."
            sed -i'.original' -e "s|\?|-|g" $cdsFile
            rm "./bustedPHResults/"$prefix"/"$prefix"_"$orthogroupNumber"_BUSTEDPH.fas"
            cat $cdsFile $pathToTrees$treeFile >> "./bustedPHResults/"$prefix"/"$prefix"_"$orthogroupNumber"_BUSTEDPH.fas"
            export inputFile="./bustedPHResults/"$prefix"/"$prefix"_"$orthogroupNumber"_BUSTEDPH.fas"
            # Fix the periods in the gene names of the input file (where is says .p1 or similar)
            #sed -i 's/\./_/g' $inputFile
            # sed -i 's/\.p/_p/g' ./bustedPHResults/parsimony/parsimony_OG0008331_BUSTEDPH.fas
            # HYPHYMPI /workdir/mb2337/cephalotesComparativeGenomics/bustedPHResults/hyphy-analyses/BUSTED-PH/BUSTED-PH.bf --alignment ./bustedPHResults/parsimony/parsimony_OG0013666_BUSTEDPH.fas --srv Yes --branches Foreground
            HYPHYMPI /workdir/mb2337/cephalotesComparativeGenomics/bustedPHResults/hyphy-analyses/BUSTED-PH/BUSTED-PH.bf --alignment $inputFile --srv Yes --branches Foreground
        else
            echo "."
        fi
    else
        echo "."
    fi
  fi
done < $1
