#!/bin/bash

# In this file:           #In BUSTEDPHchunks
#   $1                     the chunked file listing CDS files
#   $2                     the iteration we're on

# Line looks like: 15_BUSTEDPHPermutations/1_run/labelled/HOG0001333_tree.txt
while read -r line;
do
  orthogroupNumber=`echo "$line" | awk -F'/' '{print ($4)}' | awk -F'_' '{print ($1)}'`

  echo The orthogroup number is $orthogroupNumber
  export treeFile=15_BUSTEDPHPermutations/$2"_run/labelled/"$orthogroupNumber"_tree.txt"
  export cdsFile=06_AlignedNucleotideOrthogroups/alignedOrthogroupNucleotideSequences/cleaned/cleaned_$orthogroupNumber.fa
  export outputFile=15_BUSTEDPHPermutations/$2"_run/labelled/"$orthogroupNumber"_bustedPHResults.json"



  # Run RELAX:
  echo Running BUSTED-PH on $cdsFile and $treeFile.

  #HYPHYMPI /workdir/mb2337/cephalotesComparativeGenomics/09_bustedPHResults/hyphy-analyses/BUSTED-PH/BUSTED-PH.bf --alignment $inputFile --srv Yes --branches Foreground

  ~/miniconda3/bin/HYPHYMPI /workdir/mb2337/cephalotesComparativeGenomics/09_bustedPHResults/hyphy-analyses/BUSTED-PH/BUSTED-PH.bf --alignment $cdsFile --tree $treeFile --srv Yes --branches Foreground --output $outputFile

done < $1
