#!/bin/bash

# The goal of this script is to extract coding sequences from the newly sequenced Cephalotes genomes, using the .gff3 genome annotation file for Cephalotes varians.

# Run this script as extractCDSwithGFF <path to list of sample names> <path to .gff3 file>

# I need to extract the coding sequences for each species using the C. varians GFF file, then concatenate them into full coding sequences.
# Add bedtools to path:
export PATH=/programs/bedtools2-2.29.2/bin:$PATH

# Make a folder for outputs:
mkdir ./codingSequences/

# Filter the C. varians .gff3 file to include only coding sequences (not 5' UTRs, etc.):
export gffFile=$2
cat $gffFile | grep CDS > cdsOnly.gff3

# Extract all the cds sequences, iterating across all the samples:
while read -r line;
do
  export inputFasta="./consensusSequences/"$line"Consensus.fa"
  echo starting CDS extraction on $inputFasta at `date` >> cdsLog.txt
  export outputFile="./codingSequences/"$line"_cds.fasta"
  bedtools getfasta -fi $inputFasta -bed cdsOnly.gff3 -fo $outputFile

  echo finished CDS extraction on $inputFasta at `date` >> cdsLog.txt

  # Get all the features:
  bedtools getfasta -fi $inputFasta -bed $gffFile -name -fo "./codingSequences/"$line"_allFeatures.fasta"

  # Concatenate the individual CDS chunks into full length sequences:
  #/programs/gffread-0.9.12/gffread/gffread -x "./codingSequences/"$line"_fullLength.fasta" -g $inputFasta $2
  echo finished CDS extraction ***and concatentation*** on $inputFasta at `date` >> cdsLog.txt

done < $1

rm cdsOnly.gff3
